// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function AddYouTubeVideo(arg1) {
  return window['go']['main']['App']['AddYouTubeVideo'](arg1);
}

export function CancelLessonProcessing(arg1) {
  return window['go']['main']['App']['CancelLessonProcessing'](arg1);
}

export function ClearAllPlaybackProgress() {
  return window['go']['main']['App']['ClearAllPlaybackProgress']();
}

export function ClearPlaybackProgress(arg1) {
  return window['go']['main']['App']['ClearPlaybackProgress'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DownloadGPUAcceleration() {
  return window['go']['main']['App']['DownloadGPUAcceleration']();
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function ExportBackupData() {
  return window['go']['main']['App']['ExportBackupData']();
}

export function GetGPUInfo() {
  return window['go']['main']['App']['GetGPUInfo']();
}

export function GetHardwareInfo() {
  return window['go']['main']['App']['GetHardwareInfo']();
}

export function GetInstalledModels() {
  return window['go']['main']['App']['GetInstalledModels']();
}

export function GetLesson(arg1) {
  return window['go']['main']['App']['GetLesson'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStreamURL(arg1) {
  return window['go']['main']['App']['GetStreamURL'](arg1);
}

export function GetYouTubeVideos() {
  return window['go']['main']['App']['GetYouTubeVideos']();
}

export function ImportBackupData() {
  return window['go']['main']['App']['ImportBackupData']();
}

export function ImportLocalModel(arg1) {
  return window['go']['main']['App']['ImportLocalModel'](arg1);
}

export function MarkSentenceDifficult(arg1, arg2) {
  return window['go']['main']['App']['MarkSentenceDifficult'](arg1, arg2);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ProcessLesson(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessLesson'](arg1, arg2, arg3, arg4);
}

export function ProcessYouTubeLesson(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessYouTubeLesson'](arg1, arg2, arg3, arg4);
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function RemoveYouTubeVideo(arg1) {
  return window['go']['main']['App']['RemoveYouTubeVideo'](arg1);
}

export function SaveDictationAttempt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDictationAttempt'](arg1, arg2, arg3);
}

export function SavePlaybackProgress(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SavePlaybackProgress'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanFiles() {
  return window['go']['main']['App']['ScanFiles']();
}

export function SelectFolderDialog() {
  return window['go']['main']['App']['SelectFolderDialog']();
}

export function SelectModelFile() {
  return window['go']['main']['App']['SelectModelFile']();
}

export function SetActiveFolder(arg1) {
  return window['go']['main']['App']['SetActiveFolder'](arg1);
}

export function ToggleSentenceStar(arg1, arg2) {
  return window['go']['main']['App']['ToggleSentenceStar'](arg1, arg2);
}

export function UpdateSentenceVisibility(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSentenceVisibility'](arg1, arg2, arg3);
}
