// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {application} from '../models';
import {study} from '../models';
import {library} from '../models';

export function AddFolder(arg1:string):Promise<Array<string>>;

export function AddYouTubeVideo(arg1:string):Promise<media.MediaItem>;

export function ApplyUpdate():Promise<void>;

export function CancelLessonProcessing(arg1:string):Promise<boolean>;

export function CheckUpdate():Promise<application.UpdateInfo>;

export function ClearAllPlaybackProgress():Promise<void>;

export function ClearPlaybackProgress(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DownloadGPUAcceleration():Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string):Promise<void>;

export function ExportBackupData():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetGPUInfo():Promise<study.GPUInfo>;

export function GetHardwareInfo():Promise<study.HardwareInfo>;

export function GetInstalledModels():Promise<Array<study.ModelInfo>>;

export function GetLesson(arg1:string):Promise<study.Lesson>;

export function GetSettings():Promise<library.AppSettings>;

export function GetStreamURL(arg1:string):Promise<string>;

export function GetYouTubeVideos():Promise<Array<media.MediaItem>>;

export function ImportBackupData():Promise<number>;

export function ImportLocalModel(arg1:string):Promise<study.ModelInfo>;

export function MarkSentenceDifficult(arg1:string,arg2:number):Promise<study.Lesson>;

export function OpenFileInExplorer(arg1:string):Promise<void>;

export function ProcessLesson(arg1:string,arg2:string,arg3:string,arg4:string):Promise<study.Lesson>;

export function ProcessYouTubeLesson(arg1:string,arg2:string,arg3:string,arg4:string):Promise<study.Lesson>;

export function RemoveFolder(arg1:string):Promise<Array<string>>;

export function RemoveYouTubeVideo(arg1:string):Promise<void>;

export function RenameMediaFile(arg1:string,arg2:string):Promise<media.MediaItem>;

export function RenameYouTubeVideo(arg1:string,arg2:string):Promise<void>;

export function RestartApp():Promise<void>;

export function SaveDictationAttempt(arg1:string,arg2:string,arg3:study.DictationAttempt):Promise<study.Lesson>;

export function SaveLesson(arg1:study.Lesson):Promise<void>;

export function SavePlaybackProgress(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;

export function SaveSettings(arg1:library.AppSettings):Promise<void>;

export function ScanFiles():Promise<Array<media.MediaItem>>;

export function SelectFolderDialog():Promise<string>;

export function SelectModelFile():Promise<string>;

export function SetActiveFolder(arg1:string):Promise<void>;

export function ToggleSentenceStar(arg1:string,arg2:string):Promise<study.Lesson>;

export function UpdateSentenceVisibility(arg1:string,arg2:string,arg3:boolean):Promise<study.Lesson>;
